DATABASE:
  NAME: dbo
  TABLE_NAME:
  - VMAHV_migration
  - gieo_key_values
  - VMware VM
  - Nutanix VM
  HOST: localhost
  USERNAME: root
  PASSWORD: Hackathon@2024
  PORT: 3306
THRESHOLDS:
  THRESHOLD_THREADS_RUNNING: 50
  THRESHOLD_THREADS_CONNECTED: 200
  THRESHOLD_SLOW_QUERIES: 100
  THRESHOLD_LOCKED_THREADS: 10
  CPU_THRESHOLD: 50
  MEMORY_THRESHOLD: 95
  IO_THRESHOLD: 50
  CONNECTIONS_THRESHOLD: 10
SAFE_TIME_VALUES:
  CHECK_INTERVAL: 10 #seconds
BATCH_SIZE_VALUES:
  MIN_BATCH_SIZE: 100
  MAX_BATCH_SIZE: 1000
  STEP_SIZE : 10
  MAX_TIME_PER_BATCH: 1
MAINTENANCE_WINDOW:
  MW_START_DATE: 22-06-2024
  MW_START_TIME: "08:00:00" #UTC 24 hours time format
  MW_DURATION: 14440 #seconds
